.\" Copyright Petr Hracek, 2015
.\"
.\" This page is distributed under GPL.
.\"
.TH preupg 1 2015-03-01 "" "Linux User's Manual"
.SH NAME
preupg \- Preupgrade assistant performs assessment of the system from
the "upgradeability" point of view

.SH SYNOPSIS
\fBpreupg used in case of one installed contents on source system

\fBpreupg [-l, --list-contents]

\fBpreupg [-d, --debug] [--skip-common] [-s, --scan PATH] [-m, --mode MODE] [--force] [--text] [--kickstart]

\fBpreupg [-v, --verbose] [--riskcheck]

\fBpreupg [-c, --contents PATH]

\fBpreupg [--cleanup]

.SH DESCRIPTION
\fBpreupg\fP is the main binary of Preupgrade Assistant.

.SH OPTIONS
.TP
.B \-c, --contents PATH
Generates a content for preupgrade assistant.
.TP
.B \-d, --debug
Makes preupgrade assistant log lots of debugging information.
.TP
.B \-\-force
Suppress user interaction.
.TP
.B \-\-kickstart
Generate kickstart.
.TP
.B \-l, --list
Shows list of installed contents
.TP
.B \-m, --mode MODE
Select one (or both) from the possible modes: \fBmigrate\fR or \fBupgrade\fR. Both modes are used by default. \fBupgrade\fR is used for in-place upgrades on the same machine by \fIfedup\fR or \fIredhat-upgrade-tool\fR. \fBmigrate\fR is used for migration with kickstart with new clean installation, with settings of the new system as close as possible to settings of original system.
.TP
.B \-s, --scan PATH
Executes selected assessment taken from list option.
.TP
.B --skip-common
Skips generating common log files used during assessment.
.TP
.B --riskcheck
Returns value which depends on INPLACE RISK results.
If verbose mode is mentioned then shows all inplace risks generated during assessment.
Return values are 0 for NONE, SLIGHT risks or 1 for MEDIUM, HIGH risks or 2 for EXTREME risk.
.TP
.B \-\-text
Convert HTML results to text form by elinks, lynx or w3m.
.TP
.B \-v, --verbose
Shows more information during assessment. Verbose can be repeated more times.

.SH NOTES
All common log files are stored in /var/cache/preupgrade/common directory.
Assessment results are stored in /root/preupgrade directory. Tarballs with all assessments are stored in directory /root/preupgrade-results.

.SH AUTHORS
Petr Hracek, <phracek@redhat.com> (man page)
