.\" Copyright Petr Hracek, 2014
.\"
.\" This page is distributed under GPL.
.\"
.TH preupg 1 2014-03-18 "" "Linux User's Manual"
.SH NAME
preupg \- Preupgrade assistant performs assessment of the system from
the "upgradeability" point of view 

.SH SYNOPSIS
\fBpreupg used in case of one installed contents on source system

\fBpreupg [-l, --list-contents] 

\fBpreupg [-d, --debug] [--skip-common] [-s, --scan] PATH

\fBpreupg [-d, --debug] [--skip-common] [-a, --apply] 

\fBpreupg [-v, --verbose] [--riskcheck]

\fBpreupg [-c, --contents] path to contents

.SH DESCRIPTION
\fBpreupg\fP is the main binary of Preupgrade Assistant.

.SH OPTIONS
.TP
.B \-d, --debug
makes preupgrade assistant log lots of debugging information
.TP
.B --skip-common
skips generating common log files used during assessment
.TP
.B \-l, --list
shows list of installed contents
.TP
.B \-s, --scan [PATH]
executes selected assessment taken from list option
.TP
.B --apply
executes on target system
.TP
.B --riskcheck
returns value which depends on INPLACE RISK results.
If verbose mode is mentioned then shows all inplace risks generated during assessment.
Return values are 0 for NONE, SLIGHT risks or 1 for MEDIUM, HIGH risks or 2 for EXTREME risk.
.TP
.B \-v, --verbose
shows more information during assessment. Verbose can be repeated more times
.TP
.B \-c, --contents
generates a content for preupgrade assistant

.SH NOTES
All common log files are stored in /var/cache/preupgrade/common directory.
Assessment results are stored in /root/preupgrade directory. Tarballs with all assessments are stored in directory /root/preupgrade-results.

.SH AUTHORS
Petr Hracek, <phracek@redhat.com> (man page)
