#!/usr/bin/python -tt
# -*- coding: utf-8 -*-


import sys
from preup.cli import CLI
from preup.application import Application
from preup.conf import Conf
from preup import settings

#preupgrade_binary="/usr/bin/preupgrade-oscap"


def main():
    cli = CLI()
    conf = Conf(cli.opts, settings, cli)
    app = Application(conf)
    ret = 0
    if cli.opts.debug:
        ret = app.run()
    else:
        try:
            ret = app.run()
        except Exception as ex:
            cli.parser.error(str(ex))
    return ret


if __name__ == "__main__":
    sys.exit(main())
