#!/usr/bin/python2 -tt
# -*- coding: utf-8 -*-


import sys
from preup_creator.cli import CLICreator
from preup_creator.conf import ConfCreator
from preup_creator.application import Application
from preup import settings


def main():
    cli_creator = CLICreator()
    conf = ConfCreator(cli_creator.opts, settings, cli_creator)
    app = Application(conf)
    ret = 0
    try:
        ret = app.run()
    except KeyboardInterrupt:
        print ('\nContent creation was interrupted by user.\n')
        return 1
    #except Exception as ex:
    #    cli_creator.parser.error(str(ex))
    return ret


if __name__ == "__main__":
    sys.exit(main())