#!/usr/bin/python2 -tt
# -*- coding: utf-8 -*-


import sys
from preup_creator.cli import CLICreator
from preup_creator.conf import ConfCreator
from preup import settings

#preupgrade_binary="/usr/bin/preupgrade-oscap"


def main():
    cli = CLICreator()
    conf = ConfCreator(cli.opts, settings, cli)
    app = Application(conf)
    ret = 0
    if cli.opts.debug:
        ret = app.run()
    else:
        try:
            ret = app.run()
        except KeyboardInterrupt:
            print '\nAssessment interrupted.'
            return 1
        except Exception as ex:
            cli.parser.error(str(ex))
    return ret


if __name__ == "__main__":
    sys.exit(main())
