#!/bin/bash

# Create source tarrball using setuptools.

set -e

# ensure that current working directory is OK
pushd "$(dirname "$(realpath "$0")")" > /dev/null

# get information about source
NAME="$(      python setup.py --name)"
VERSION="$(   python setup.py --version)"

# use standard setup.py sdist to generate tar archive
python setup.py sdist --formats=gztar

# provide useful output
echo "$PWD/dist/${NAME}-${VERSION}.tar.bz2"

popd > /dev/null

