#!/bin/bash

. /usr/share/preupgrade/common.sh

#END GENERATED SECTION

##
# Long story short:
#
#    If you want to do some checks or automatic actions when execute
#    redhat-upgrade-tool, before the reboot, this is what you need to do.
#    Basically just copy executable files into the $PREUPGRADE_SCRIPT_DIR.

###########################################################
# FUNCTIONS AND VARIABLES                                 #
###########################################################


#
# The name of the pre-upgrade script. Change the name to the script you
# would like to execute during pre-upgrade phase when redhat-upgrade-tool is
# executed. The script is expected to be in the same dir as the module.
# IMPORTANT:
#   Put here just the FILENAME. Do not put here path to the file - which is
#   supposed to be in the same directory as the module in this case.
#
PRE_UPGRADE_SCRIPT="<PRE_UPGRADE_SCRIPT>"

#
# Update this path as needed regarding the name of the module
#
_PREUPGRADE_SCRIPT_DIR="$PREUPGRADE_SCRIPT_DIR/3rdparty/mycustom/05_add_pre_upgrade_script"
_DST_PREUPGRADE_SCRIPT_PATH="$_PREUPGRADE_SCRIPT_DIR/$PRE_UPGRADE_SCRIPT"

install_preupgrade_script() {
    mkdir -p "$_PREUPGRADE_SCRIPT_DIR"
    cp -a "$PRE_UPGRADE_SCRIPT" "$_DST_PREUPGRADE_SCRIPT_PATH"
    chmod +x "$_DST_PREUPGRADE_SCRIPT_PATH"
    log_info "The pre-upgrade script is registered: $_DST_PREUPGRADE_SCRIPT_PATH"
}

###########################################################
# MAIN                                                    #
###########################################################

if [[ ! -e "$PRE_UPGRADE_SCRIPT" ]]; then
  # The file is required, so log "error" and exit with "error" when the file doesn't
  # exist.
  log_error "The $PRE_UPGRADE_SCRIPT is required but do not exists."
  exit_error
fi

# install the pre-upgrade script; modify the code as you wish
install_preupgrade_script

exit_fixed

