#!/usr/bin/python2
import os
import sys
import preupg.ui.libpath

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "preupg.ui.settings")

    from django.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)
